version: v3
name: "space-trouble-api"
services:
  backend:
    image: space-trouble-api:dev
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./sql:/home/app/sql
      - ./configs:/home/app/configs
    command:
      - -config /home/app/configs/sample.yaml

  postgres:
    container_name: postgres
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_USER=space
      - POSTGRES_PASSWORD=space
      - POSTGRES_DB=space
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U space" ]
      interval: 1s
      timeout: 5s
      retries: 10